apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-devfile-sample-ehok
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-devfile-sample-ehok
    app.kubernetes.io/part-of: veda-nodejs-sample2
  name: nodejs-devfile-sample-ehok
  namespace: veda2019subs-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: nodejs-devfile-sample-ehok
    weight: null
status: {}
