apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-devfile-sample-ehok
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-devfile-sample-ehok
    app.kubernetes.io/part-of: veda-nodejs-sample2
  name: nodejs-devfile-sample-ehok
  namespace: veda2019subs-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs-devfile-sample-ehok
status:
  loadBalancer: {}
